pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling code'
            }
        }

        stage('Build') {
            steps {
                sh 'echo Build started'
            }
        }

        stage('Test') {
            steps {
                sh 'echo Running tests'
            }
        }
    }
}
